terralist/terralist

internal/server/repositories/module.go

Ideally unit tests would catch these bugs
fixes #35

Fix Module upload version bug

---

cmd/terralist/server/flags.go
cmd/terralist/server/server.go
example.yaml
internal/server/server.go

This PR removes the `storage-resolver` flag and adds the `modules-storage-resolver` and `providers-storage-resolver` flags. 
This feature allows the user to use different resolvers for modules and providers.
_Note_: This feature does not allow multiple instances of the same resolver (e.g. different S3 buckets for modules and providers).

feat(resolver)!: Support different resolvers for modules and providers

---

cmd/terralist/server/flags.go
cmd/terralist/server/server.go
docs/CONFIGURATION.md
go.mod
go.sum
pkg/database/creator.go
pkg/database/factory/factory.go
pkg/database/mysql/config.go
pkg/database/mysql/creator.go

This will add MySQL support. Basically it's copy/paste of PostgreSQL code.
MySQL cannot have TEXT fields as unique indexes, so I've limited Name to 255 characters and UUID to 36. Apparently PostgreSQL/SQLite can work with it too, but please let me know if there are some concerns.
And mysql-url must have parseTime=true (https://github.com/go-sql-driver/mysql#timetime-support)

feat(database): Add MySQL support

---

internal/server/models/authority/key.go

Fixes #109.
During the investigation, I analyzed two possible solutions:
- Increasing the size of the string (the current one);
```go
AsciiArmor     string `gorm:"size:10000,not null"`
TrustSignature string `gorm:"size:10000,not null"`
```
- Changing the column type to `text`;
```go
AsciiArmor     string `gorm:"type:text,not null"`
TrustSignature string `gorm:"type:text,not null"`
```
Both solutions work fine with the currently supported backends (PostgreSQL, MySQL, SQLite). 
I kept the first option because it's backend-agnostic and lets gorm choose which backend-specific type is more appropriate for the given size. For example, in this scenario, gorm picks `longtext` (max. length 2<sup>32</sup> − 1) for MySQL, even though `text` (max. length 2<sup>16</sup> - 1) is enough; for PostgreSQL …

fix: MySQL data too long for large strings

---

internal/server/repositories/authority.go

The loop variable is reassigned in each iteration. After the `for` loop ends, only the last value will be referenced.

fix: Take reference of loop variables properly

---

cmd/terralist/server/flags.go
cmd/terralist/server/server.go
docs/CONFIGURATION.md
internal/server/config.go
internal/server/server.go

This PR introduces support for HTTPS.
Terraform requires the registry to be served over HTTPS. Because of that, up until now, Terralist was forced to be placed behind a reverse proxy that handled the SSL certificate.

feat: Add support for HTTPS

---

Dockerfile
docker-entrypoint.sh

Closes #123.
This change allows the Terralist image to run other commands than the `terralist`-specific ones while following the containerization best practices. It also introduces a custom user to run the `terralist` process, stepping down from the root privileges.

feat(build): Extend Docker image with custom entrypoint

---

web/src/api/apiKeys.ts
web/src/api/artifacts.ts
web/src/api/authorities.ts
web/src/api/keys.ts

Axios timeout is specified in number of milliseconds.
It may be hard to make timeouts configurable, because web UI needs to be rebuilt on change, and getting configuration from the server would be affected by the timeout itself.
We should ship a release with sensible defaults first, and then consider how to make it configurable.

fix(webui): Use sensible default timeout

---

pkg/auth/github/provider.go

On GitHub, the user's name is optional. If the user's name is not available, we should fallback and use the user's login name (username) instead.
Closes #192.

 fix(github): Fallback to user's login name

---

internal/server/repositories/module.go
internal/server/repositories/provider.go
web/src/pages/Artifact.svelte

This PR fixes the bug where artifacts that contains some upper-case letters in their name were not discoverable by the API.
To avoid creating a breaking change, I updated the find methods to convert the inputs to lowercase before comparing them with the values stored in the database. A more efficient approach would be to assume that everything in the database is lowercased, and lowercase the names during the creation of the modules/providers. The latter might be subject for a different PR and released in a future minor version.
Fixes #191.

fix: Modules and providers names case insensitive

---

web/src/components/ArtifactCard.svelte
web/src/components/ArtifactsGrid.svelte

This PR fixes various dashboard paginations issues:
- URLs on subsequent pages are outdated (pointing to the resources on the first page);
- Empty page (if `artifactsCount = pagesCount * itemsPerPage`);
- Faulty computation of the total number of items;
Fixes #194.

fix(webui): Malfunction of the dashboard pagination

---

web/src/components/ArtifactsGrid.svelte

This PR fixes the problem described in #194, where the pagination buttons only displays the first page.
It is actually just an unpushed commit from #198. :smiling_face_with_tear:

fix: Pagination always displays one page

---

web/src/pages/Artifact.svelte

In #196 I converted all artifact attributes to lower-case without null-checking them first. Because of that (and because the providers don't have a provider field), the artifact page for providers was crashing.

fix: Crash while rendering provider pages

---

pkg/file/fetch.go
pkg/file/inmemory.go
web/dist/.gitignore

**Related issue:** https://github.com/terralist/terralist/issues/213.
**Changes introduced**
- When creating an archive, file modes will be preserved
**Implementation**
- `pkg/file/fetch.go` `readFile` function now stats file to gather `fs.FileInfo`
- `pkg/file/fetch.go` `archiveDir` re-use `readFile` to get a file data
- `pkg/file/inmemory.go` `InMemoryFile` extended by `fs.FileInfo` struct
- `pkg/file/inmemory.go` `Archive` use [CreateHeader](https://pkg.go.dev/archive/zip#Writer.CreateHeader) method to archive files with metadata

feat: Preserve filemode

---

internal/server/controllers/module.go

Closes #223.
It looks like OpenTofu and Terraform are a bit different in their registry implementation. Terraform accepts both 200 and 204 statuses with the `X-Terraform-Get` header, but OpenTofu accepts only 204 with the same header **OR** 200 status with a JSON body.

fix: Modules download API should return status 204

---

.github/workflows/image.yml
.github/workflows/release.yml
.github/workflows/test.yml

Closes #203.
Closes #202.
Closes #201.
Closes #200.
Closes #199.
This PR upgrades the GA stack to use the recommended runtime `node20`.

chore: Upgrade GA actions versions

---

docs/dev-guide/api-reference.md

Closes #298.
I found an error in the documentation, in deleting the provider/module:
```
curl -L -X POST \
-H "Authorization: Bearer <YOUR-TOKEN>" \
http://localhost:5758/v1/api/providers/NAME/VERSION/remove
curl -L -X POST \
-H "Authorization: Bearer <YOUR-TOKEN>" \
http://localhost:5758/v1/api/providers/NAME/VERSION/remove
```

fix(docs): API reference for uploading/deleting modules and providers

---

cmd/terralist/server/flags.go
cmd/terralist/server/server.go
docs/configuration.md
pkg/auth/github/config.go
pkg/auth/github/creator.go
pkg/auth/github/provider.go

This PR adds another layer of granularity for granting access to the registry. You can now provide a list of github teams in the configuration to filter who has access. This could be useful when your organization is quite big and not everyone should have access to it.
The filter is done on the Name of the team but looks like using the slug would be cleaner.

feat: Add gh-teams flags to restrict access to some teams only

---

cmd/terralist/server/flags.go
docs/configuration.md
pkg/cli/path_flag.go

This PR adds support for PathFlags which are able to resolve a path given as a flag to an absolute path.
In this PR, a `home` flag was also added, which will be later used by Terralist to store various files.

feat(cli): Add support for path-based flags

---

cmd/terralist/server/server.go
docs/dev-guide/api-reference.md
internal/server/config.go
internal/server/controllers/module.go
internal/server/server.go

Closes #33.
This PR adds a new endpoint that allows users to upload the module files directly from the local disk, instead of asking Terralist to download them from somewhere else.
To avoid creating a breaking change, it will be a different endpoint, for now, but most probably it will be merged with the original one before v1 release.

feat(api): Upload modules with content

---

docs/dev-guide/api-reference.md
e2e/suites/modules.v1.yaml
e2e/suites/providers.v1.yaml
internal/server/controllers/module.go
internal/server/models/module/module.go
internal/server/models/provider/provider.go
internal/server/services/module.go
internal/server/services/module_test.go
internal/server/services/provider.go
internal/server/services/provider_test.go
pkg/file/fetch.go
pkg/file/fetcher.go

Closes #190.
This PR adds support for custom additional headers for modules and providers upload APIs. With this users should now be able to upload files to Terralist that are not publicly available for download.

feat(api): Accept custom HTTP headers

---

cmd/terralist/server/flags.go
cmd/terralist/server/server.go
docs/configuration.md
pkg/auth/gitlab/config.go
pkg/auth/gitlab/creator.go
pkg/auth/gitlab/provider.go

This PR adds support for Gitlab groups, similar to GitHub teams. 
New configuration `gl-groups` was added. It accepts comma separated values with the Gitlab group names

feat: added support for Gitlab groups on authentication

---

.github/workflows/test.yml

Ref https://github.com/minio/mc/issues/5206.

chore(e2e): Fix deprecated `mc config` command

---

cmd/terralist/server/flags.go
cmd/terralist/server/server.go
docs/configuration.md
pkg/auth/github/config.go
pkg/auth/github/creator.go
pkg/auth/github/provider.go

Like #289 already suggested, for supporting authentication against Github Enterprise instances only one additional flag is need. I added the `--gh-domain` flag with `github.com` as the default for backwards compatibility.
I already tested with the Docker setup against our company internal Github Enterprise instance and it worked fine.
Closes #289.

feat: Add support for Github Enterprise Domains

---

docs/artifacts-documentation.md
pkg/docs/module.go
pkg/docs/module_test.go

For me at least, this was a bug in that if `README.md` was in the same directory as ~~`main.tf`~~ any of the `*.tf` files in the module (in this case the root of the module) then the README was ignored when registering the module in Terralist. So, I rewrote the functionality, making sure it not only corrects the issue I ran into but also passes existing Unit tests to not break other existing functionality.

(enh): Enhanced logic, corrected missing README in same dir as any *.tf

---

web/package.json
web/yarn.lock

During frontend build, `vite-plugin-svelte` reports the following warning:
```
[vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.
svelte-system-info@1.0.3
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
```
After further investigations, I noticed that the package is indeed updated to 1.0.3 on npmjs.org [[1](https://www.npmjs.com/package/svelte-system-info)], but the source code is only tagged up to 1.0.1 [[2](https://github.com/rozek/svelte-system-info)] (as of now, August 27, 2025).

chore(deps): Downgrade svelte-system-info to v1.0.1
